package = "sololc:webhook"
version = "0.1.0"

authors = ["Josh Klein <gigacoderx@gmail.com>"]
description = "High-performance WASI-HTTP Webhook SDK for Sololc Runtime"
license = "Apache-2.0"

[dependencies]
"wasi:cli" = "0.2.0"
"wasi:http" = "0.2.0"
"wasi:io" = "0.2.0"
"wasi:clocks" = "0.2.0"
"wasi:random" = "0.2.0"
"wasi:filesystem" = "0.2.0"
"wasi:sockets" = "0.2.0"